"use client";

import { useState } from "react";
import { createEngagementAction } from "@/app/actions/audit-file";
import { Panel, btnPrimary } from "@/components/ui/atlas";
import { SubmitButton } from "@/components/SubmitButton";
import {
  DURATION_OPTIONS,
  ENGAGEMENT_PHASE_OPTIONS,
  FRAMEWORK_OPTIONS,
  NATURE_OPTIONS,
  YEAR_END_OPTIONS,
  generateEngagementName,
} from "@/lib/complexity";

export interface WizardLabels {
  clientLabel: string;
  yearLabel: string;
  submit: string;
  yes: string;
  no: string;
  partnerLabel: string;
  partnerNone: string;
  newEntity: string;
  newEntityHint: string;
  entityName: string;
  legalForm: string;
  listed: string;
  coCac: string;
}

/** Sentinel select value: create the entity together with the engagement. */
const NEW_ENTITY = "__new";

/**
 * Engagement creation: the identity questions only. The engagement name is
 * generated by the tool (CLIENT_PERIOD END_NATURE) and shown, not typed. The
 * nature-of-entity assessment that scales the audit file is a separate screen
 * presented after creation.
 */
export function EngagementWizard({
  clients,
  partners,
  legalForms,
  defaultClientId,
  locale,
  labels,
}: {
  clients: { id: string; name: string }[];
  partners: { id: string; name: string }[];
  legalForms: readonly string[];
  defaultClientId?: string;
  locale: "en" | "fr";
  labels: WizardLabels;
}) {
  const fr = locale === "fr";
  const currentYear = new Date().getFullYear();
  const [clientId, setClientId] = useState(defaultClientId ?? clients[0]?.id ?? NEW_ENTITY);
  const [newEntityName, setNewEntityName] = useState("");
  const [year, setYear] = useState(String(currentYear));
  const [yearEnd, setYearEnd] = useState<string>("12-31");
  const [nature, setNature] = useState<string>("statutory_audit");

  const isNewEntity = clientId === NEW_ENTITY;
  const clientName = isNewEntity ? newEntityName : (clients.find((c) => c.id === clientId)?.name ?? "");
  const generatedName = generateEngagementName(clientName, yearEnd, year || currentYear, nature);

  const input =
    "rounded-[var(--radius-atlas-sm)] border border-line-strong bg-surface px-3 py-2 text-sm text-ink outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-600/20";
  const label = "flex flex-col gap-1 text-sm text-ink-soft";

  return (
    <form action={createEngagementAction} className="flex flex-col gap-4">
      <Panel className="p-6">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          <label className={label}>
            {labels.clientLabel}
            <select
              name="clientId"
              value={clientId}
              onChange={(e) => setClientId(e.target.value)}
              required
              className={input}
              data-testid="engagement-client"
            >
              {clients.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.name}
                </option>
              ))}
              <option value={NEW_ENTITY}>{labels.newEntity}</option>
            </select>
          </label>
          <label className={label}>
            {labels.yearLabel}
            <input
              name="fiscalYear"
              type="number"
              min="2000"
              max="2100"
              value={year}
              onChange={(e) => setYear(e.target.value)}
              required
              className={input}
              data-testid="engagement-year"
            />
          </label>
          <label className={label}>
            {fr ? "Date de clôture" : "Year-end period"}
            <select
              name="yearEnd"
              value={yearEnd}
              onChange={(e) => setYearEnd(e.target.value)}
              required
              className={input}
              data-testid="engagement-period-end"
            >
              {YEAR_END_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>
                  {fr ? o.fr : o.en}
                </option>
              ))}
            </select>
          </label>
          <label className={label}>
            {fr ? "Durée (mois)" : "Duration (months)"}
            <select name="durationMonths" defaultValue="12" required className={input} data-testid="engagement-duration">
              {DURATION_OPTIONS.map((d) => (
                <option key={d} value={d}>
                  {d} {fr ? "mois" : "months"}
                </option>
              ))}
            </select>
          </label>
          <label className={label}>
            {fr ? "Nature de la mission" : "Nature of engagement"}
            <select
              name="nature"
              value={nature}
              onChange={(e) => setNature(e.target.value)}
              required
              className={input}
              data-testid="engagement-nature"
            >
              {NATURE_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>
                  {fr ? o.fr : o.en}
                </option>
              ))}
            </select>
          </label>
          <label className={label}>
            {fr ? "Phase des travaux" : "Phase of the work"}
            <select name="engagementPhase" defaultValue="year_end" required className={input} data-testid="engagement-work-phase">
              {ENGAGEMENT_PHASE_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>
                  {fr ? o.fr : o.en}
                </option>
              ))}
            </select>
          </label>
          <label className={label}>
            {fr ? "Référentiel comptable" : "Reporting framework"}
            <select name="framework" defaultValue="syscohada" required className={input} data-testid="engagement-framework">
              {FRAMEWORK_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>
                  {fr ? o.fr : o.en}
                </option>
              ))}
            </select>
          </label>
          <label className={label}>
            {fr ? "Première année du mandat ?" : "First-year (initial) engagement?"}
            <select name="firstYear" defaultValue="no" required className={input} data-testid="engagement-first-year">
              <option value="no">{labels.no}</option>
              <option value="yes">{labels.yes}</option>
            </select>
          </label>
          <label className={label}>
            {labels.partnerLabel}
            <select name="partnerId" defaultValue="" className={input} data-testid="engagement-partner">
              <option value="">{labels.partnerNone}</option>
              {partners.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.name}
                </option>
              ))}
            </select>
          </label>
        </div>

        {isNewEntity ? (
          <div className="mt-4 rounded-[var(--radius-atlas-sm)] border border-line bg-surface-2 p-4">
            <p className="mb-3 text-xs font-semibold text-ink-soft">{labels.newEntityHint}</p>
            <div className="flex flex-wrap items-end gap-4">
              <label className={label}>
                {labels.entityName}
                <input
                  name="newEntityName"
                  required
                  value={newEntityName}
                  onChange={(e) => setNewEntityName(e.target.value)}
                  className={input}
                  data-testid="new-entity-name"
                />
              </label>
              <label className={label}>
                {labels.legalForm}
                <select name="newEntityLegalForm" defaultValue="SA" className={input} data-testid="new-entity-legal-form">
                  {legalForms.map((form) => (
                    <option key={form} value={form}>
                      {form}
                    </option>
                  ))}
                </select>
              </label>
              <label className="flex items-center gap-2 pb-2 text-sm text-ink-soft">
                <input type="checkbox" name="newEntityListed" /> {labels.listed}
              </label>
              <label className="flex items-center gap-2 pb-2 text-sm text-ink-soft">
                <input type="checkbox" name="newEntityCoCac" /> {labels.coCac}
              </label>
            </div>
          </div>
        ) : null}

        <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-line pt-4">
          <div className="min-w-0">
            <span className="block text-[10.5px] font-bold uppercase tracking-[0.08em] text-muted">
              {fr ? "Nom de la mission (généré)" : "Engagement name (generated)"}
            </span>
            <span
              className="block truncate font-mono text-[13px] font-semibold text-ink"
              data-testid="engagement-name"
            >
              {generatedName || "—"}
            </span>
          </div>
          <SubmitButton className={btnPrimary} testId="create-engagement">
            {labels.submit}
          </SubmitButton>
        </div>
      </Panel>
    </form>
  );
}
