"use client";

import { useState } from "react";
import { createEngagementAction } from "@/app/actions/audit-file";
import { Panel, btnPrimary } from "@/components/ui/atlas";
import { SubmitButton } from "@/components/SubmitButton";
import { NATURE_OPTIONS, generateEngagementName } from "@/lib/complexity";

export interface WizardLabels {
  clientLabel: string;
  yearLabel: string;
  submit: string;
}

/**
 * Engagement creation, reduced to the three identity questions: the client
 * name (typed directly — an existing client is matched by name, a new name
 * creates the entity), the fiscal year, and the nature of the engagement
 * (free text when "Other"). The engagement name is generated by the tool.
 * The team is added on its own screen after creation, and the first-year
 * question lives in the nature-of-entity questionnaire.
 */
export function EngagementWizard({
  clients,
  defaultClientName,
  locale,
  labels,
}: {
  clients: { id: string; name: string }[];
  defaultClientName?: string;
  locale: "en" | "fr";
  labels: WizardLabels;
}) {
  const fr = locale === "fr";
  const currentYear = new Date().getFullYear();
  const [clientName, setClientName] = useState(defaultClientName ?? "");
  const [year, setYear] = useState(String(currentYear));
  const [nature, setNature] = useState<string>("statutory_audit");
  const [natureText, setNatureText] = useState("");

  const natureForName =
    nature === "other" && natureText.trim() ? natureText.trim().toUpperCase() : nature;
  const generatedName = generateEngagementName(clientName, "12-31", year || currentYear, natureForName);
  const isKnownClient = clients.some((c) => c.name.trim().toLowerCase() === clientName.trim().toLowerCase());

  const input =
    "rounded-[var(--radius-atlas-sm)] border border-line-strong bg-surface px-3 py-2 text-sm text-ink outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-600/20";
  const label = "flex flex-col gap-1 text-sm text-ink-soft";

  return (
    <form action={createEngagementAction} className="flex flex-col gap-4">
      <Panel className="p-6">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
          <label className={label}>
            {labels.clientLabel}
            <input
              name="clientName"
              value={clientName}
              onChange={(e) => setClientName(e.target.value)}
              required
              maxLength={80}
              list="client-names"
              placeholder={fr ? "Saisir ou choisir un client" : "Type or pick a client"}
              className={input}
              data-testid="engagement-client"
            />
            <datalist id="client-names">
              {clients.map((c) => (
                <option key={c.id} value={c.name} />
              ))}
            </datalist>
            <span className="text-xs text-muted">
              {clientName.trim() === ""
                ? " "
                : isKnownClient
                  ? fr
                    ? "Client existant"
                    : "Existing client"
                  : fr
                    ? "Nouveau client — l’entité sera créée"
                    : "New client — the entity will be created"}
            </span>
          </label>
          <label className={label}>
            {labels.yearLabel}
            <input
              name="fiscalYear"
              type="number"
              min="2000"
              max="2100"
              value={year}
              onChange={(e) => setYear(e.target.value)}
              required
              className={input}
              data-testid="engagement-year"
            />
          </label>
          <label className={label}>
            {fr ? "Nature de la mission" : "Nature of engagement"}
            <select
              name="nature"
              value={nature}
              onChange={(e) => setNature(e.target.value)}
              required
              className={input}
              data-testid="engagement-nature"
            >
              {NATURE_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>
                  {fr ? o.fr : o.en}
                </option>
              ))}
            </select>
            {nature === "other" ? (
              <input
                name="natureText"
                value={natureText}
                onChange={(e) => setNatureText(e.target.value)}
                required
                maxLength={60}
                placeholder={fr ? "Préciser la nature de la mission" : "Describe the nature of the engagement"}
                className={input}
                data-testid="engagement-nature-text"
              />
            ) : null}
          </label>
        </div>

        <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-line pt-4">
          <div className="min-w-0">
            <span className="block text-[10.5px] font-bold uppercase tracking-[0.08em] text-muted">
              {fr ? "Nom de la mission (généré)" : "Engagement name (generated)"}
            </span>
            <span
              className="block truncate font-mono text-[13px] font-semibold text-ink"
              data-testid="engagement-name"
            >
              {generatedName || "—"}
            </span>
          </div>
          <SubmitButton className={btnPrimary} testId="create-engagement">
            {labels.submit}
          </SubmitButton>
        </div>
      </Panel>
    </form>
  );
}
