// Working-paper template registry (master spec §9.1) — v1 ships templates as
// versioned code definitions rendered to .docx at instantiation time. Template
// changes never mutate documents already instantiated: the generated bytes are
// frozen in document_version, stamped with the template id + version in `note`.

import type { Locale } from "@/lib/i18n";

export interface WorkpaperTemplate {
  id: string;
  version: number;
  purpose: Record<Locale, string>;
  /** Checklist items rendered as actionable rows in the document. */
  items: Record<Locale, string[]>;
}

const GENERIC: WorkpaperTemplate = {
  id: "generic",
  version: 1,
  purpose: {
    en: "Document the work performed for this file-index area, the evidence obtained and the conclusion reached, in accordance with the applicable ISA requirements.",
    fr: "Documenter les travaux réalisés pour cette rubrique du dossier, les éléments probants obtenus et la conclusion, conformément aux normes ISA applicables.",
  },
  items: {
    en: [
      "State the objective of the work in this area.",
      "Describe the procedures performed and evidence obtained.",
      "Record exceptions or matters arising and how they were resolved or routed.",
      "Conclude on whether the objectives for this area have been achieved.",
    ],
    fr: [
      "Indiquer l'objectif des travaux pour cette rubrique.",
      "Décrire les procédures réalisées et les éléments probants obtenus.",
      "Consigner les anomalies ou points relevés et leur traitement.",
      "Conclure sur l'atteinte des objectifs de la rubrique.",
    ],
  },
};

const D31: WorkpaperTemplate = {
  id: "P1.1-acceptance",
  version: 1,
  purpose: {
    en: "Document the firm's acceptance or continuance decision for this engagement (ISA 220, ISQM 1, IESBA Code). The engagement cannot move to planning until the partner signs the acceptance conclusion.",
    fr: "Documenter la décision d'acceptation ou de maintien de la mission (ISA 220, ISQM 1, Code IESBA). La mission ne peut passer à la planification qu'après signature de la conclusion d'acceptation par l'associé.",
  },
  items: {
    en: [
      "Assess client integrity (owners, management, reputation, business practices).",
      "Confirm the firm's competence, capabilities and resources for the engagement.",
      "Perform the conflicts check against the firm's client base.",
      "Complete the AML/KYC checklist for the client and its beneficial owners.",
      "Record communication with the predecessor auditor (with client permission; NOCLAR information must be shared without consent).",
      "Confirm independence of the firm and the engagement team.",
      "Rate the engagement risk (Low / Moderate / High) and justify the rating.",
      "Partner conclusion: accept / continue the engagement.",
    ],
    fr: [
      "Évaluer l'intégrité du client (actionnaires, direction, réputation, pratiques).",
      "Confirmer la compétence, les capacités et les ressources du cabinet pour la mission.",
      "Effectuer la vérification des conflits d'intérêts sur le portefeuille du cabinet.",
      "Compléter la liste de contrôle LBC/FT (AML/KYC) pour le client et ses bénéficiaires effectifs.",
      "Consigner la communication avec l'auditeur précédent (avec l'autorisation du client ; les informations NOCLAR doivent être communiquées sans consentement).",
      "Confirmer l'indépendance du cabinet et de l'équipe de mission.",
      "Coter le risque de la mission (Faible / Modéré / Élevé) et justifier la cotation.",
      "Conclusion de l'associé : accepter / maintenir la mission.",
    ],
  },
};

const E500_ITGC: WorkpaperTemplate = {
  id: "E1.1-itgc",
  version: 1,
  purpose: {
    en: "Test the design and operating effectiveness of general IT controls (ITGCs) over the systems relevant to financial reporting, to support reliance on automated controls and system-generated reports (ISA 315 (Revised 2019) Appendices 5–6, ISA 330).",
    fr: "Tester la conception et l'efficacité opérationnelle des contrôles généraux informatiques (CGI) sur les systèmes pertinents pour l'information financière, afin d'appuyer la confiance accordée aux contrôles automatisés et aux états générés par les systèmes (ISA 315 (révisée 2019) annexes 5–6, ISA 330).",
  },
  items: {
    en: [
      "Confirm the scope from ST4.1 (Understanding the IT Environment): applications, databases, operating systems and interfaces relevant to financial reporting.",
      "Access to programs and data: test user provisioning and de-provisioning, privileged access, password parameters and the periodic access review.",
      "Program changes: test that changes are authorised, tested, approved and segregated (developer ≠ migrator) before moving to production.",
      "Program development / acquisition: assess controls over new systems or major upgrades implemented in the period, including data migration.",
      "Computer operations: test job scheduling and monitoring, backup and restore, and IT incident management.",
      "Evaluate exceptions: assess the effect of ITGC deficiencies on planned reliance on automated controls and key reports; design compensating procedures where reliance is not supported.",
      "Conclude on ITGC reliance and document the effect on the control-testing strategy for the transaction cycles (E1) and accounts (E3).",
    ],
    fr: [
      "Confirmer le périmètre issu de ST4.1 (connaissance de l'environnement informatique) : applications, bases de données, systèmes d'exploitation et interfaces pertinents pour l'information financière.",
      "Accès aux programmes et aux données : tester la création et la désactivation des comptes, les accès privilégiés, les paramètres de mots de passe et la revue périodique des accès.",
      "Modifications des programmes : tester que les changements sont autorisés, testés, approuvés et que les fonctions sont séparées (développeur ≠ responsable de mise en production).",
      "Développement / acquisition : évaluer les contrôles sur les nouveaux systèmes ou évolutions majeures de la période, y compris la migration des données.",
      "Exploitation informatique : tester l'ordonnancement et la supervision des traitements, les sauvegardes et restaurations, et la gestion des incidents.",
      "Évaluer les exceptions : apprécier l'incidence des faiblesses de CGI sur la confiance prévue dans les contrôles automatisés et les états clés ; concevoir des procédures compensatoires si nécessaire.",
      "Conclure sur la confiance accordée aux CGI et documenter l'incidence sur la stratégie de tests de contrôles des cycles (E1) et des comptes (E3).",
    ],
  },
};

const E510_APP_CONTROLS: WorkpaperTemplate = {
  id: "E1.2-application-controls",
  version: 1,
  purpose: {
    en: "Test the key automated application controls, interface controls and IT-dependent manual controls (including system-generated reports) on which the audit strategy places reliance (ISA 330).",
    fr: "Tester les contrôles applicatifs automatisés clés, les contrôles d'interfaces et les contrôles manuels dépendants de l'informatique (y compris les états générés par les systèmes) sur lesquels la stratégie d'audit s'appuie (ISA 330).",
  },
  items: {
    en: [
      "Identify the automated controls and key system-generated reports relied upon, per significant transaction class (E1) and account section (E3).",
      "For each automated control, test the configuration/parameters and one instance of operation (benchmarking is permitted only where ITGCs (E1.1) are effective).",
      "Test the completeness and accuracy of key system-generated reports used as audit evidence or within management's controls.",
      "Test interface controls over data transfers between in-scope systems (completeness, accuracy, error handling).",
      "Evaluate exceptions: reassess control risk and extend substantive procedures where reliance is not supported.",
      "Conclude on application-control reliance and update the risk–response mapping (ST6.1) where the strategy changes.",
    ],
    fr: [
      "Identifier les contrôles automatisés et les états clés générés par les systèmes sur lesquels l'audit s'appuie, par flux significatif (E1) et par section de comptes (E3).",
      "Pour chaque contrôle automatisé, tester le paramétrage et une occurrence de fonctionnement (l'approche « benchmark » n'est admise que si les CGI (E1.1) sont efficaces).",
      "Tester l'exhaustivité et l'exactitude des états clés générés par les systèmes utilisés comme éléments probants ou dans les contrôles de la direction.",
      "Tester les contrôles d'interfaces sur les transferts de données entre systèmes du périmètre (exhaustivité, exactitude, traitement des rejets).",
      "Évaluer les exceptions : réapprécier le risque lié aux contrôles et étendre les procédures de corroboration si la confiance n'est pas justifiée.",
      "Conclure sur la confiance accordée aux contrôles applicatifs et mettre à jour le lien risques–réponses (ST6.1) si la stratégie évolue.",
    ],
  },
};

const TEMPLATES: Record<string, WorkpaperTemplate> = {
  "P1.1": D31,
  "E1.1": E500_ITGC,
  "E1.2": E510_APP_CONTROLS,
};

/** Resolve the template for a file-index code (falls back to the generic form). */
export function templateFor(code: string): WorkpaperTemplate {
  return TEMPLATES[code] ?? GENERIC;
}
