// Working-paper template registry (master spec §9.1) — v1 ships templates as
// versioned code definitions rendered to .docx at instantiation time. Template
// changes never mutate documents already instantiated: the generated bytes are
// frozen in document_version, stamped with the template id + version in `note`.

import type { Locale } from "@/lib/i18n";

export interface WorkpaperTemplate {
  id: string;
  version: number;
  purpose: Record<Locale, string>;
  /** Checklist items rendered as actionable rows in the document. */
  items: Record<Locale, string[]>;
}

const GENERIC: WorkpaperTemplate = {
  id: "generic",
  version: 1,
  purpose: {
    en: "Document the work performed for this file-index area, the evidence obtained and the conclusion reached, in accordance with the applicable ISA requirements.",
    fr: "Documenter les travaux réalisés pour cette rubrique du dossier, les éléments probants obtenus et la conclusion, conformément aux normes ISA applicables.",
  },
  items: {
    en: [
      "State the objective of the work in this area.",
      "Describe the procedures performed and evidence obtained.",
      "Record exceptions or matters arising and how they were resolved or routed.",
      "Conclude on whether the objectives for this area have been achieved.",
    ],
    fr: [
      "Indiquer l'objectif des travaux pour cette rubrique.",
      "Décrire les procédures réalisées et les éléments probants obtenus.",
      "Consigner les anomalies ou points relevés et leur traitement.",
      "Conclure sur l'atteinte des objectifs de la rubrique.",
    ],
  },
};

const D31: WorkpaperTemplate = {
  id: "D3.1-acceptance",
  version: 1,
  purpose: {
    en: "Document the firm's acceptance or continuance decision for this engagement (ISA 220, ISQM 1, IESBA Code). The engagement cannot move to planning until the partner signs the acceptance conclusion.",
    fr: "Documenter la décision d'acceptation ou de maintien de la mission (ISA 220, ISQM 1, Code IESBA). La mission ne peut passer à la planification qu'après signature de la conclusion d'acceptation par l'associé.",
  },
  items: {
    en: [
      "Assess client integrity (owners, management, reputation, business practices).",
      "Confirm the firm's competence, capabilities and resources for the engagement.",
      "Perform the conflicts check against the firm's client base.",
      "Complete the AML/KYC checklist for the client and its beneficial owners.",
      "Record communication with the predecessor auditor (with client permission; NOCLAR information must be shared without consent).",
      "Confirm independence of the firm and the engagement team.",
      "Rate the engagement risk (Low / Moderate / High) and justify the rating.",
      "Partner conclusion: accept / continue the engagement.",
    ],
    fr: [
      "Évaluer l'intégrité du client (actionnaires, direction, réputation, pratiques).",
      "Confirmer la compétence, les capacités et les ressources du cabinet pour la mission.",
      "Effectuer la vérification des conflits d'intérêts sur le portefeuille du cabinet.",
      "Compléter la liste de contrôle LBC/FT (AML/KYC) pour le client et ses bénéficiaires effectifs.",
      "Consigner la communication avec l'auditeur précédent (avec l'autorisation du client ; les informations NOCLAR doivent être communiquées sans consentement).",
      "Confirmer l'indépendance du cabinet et de l'équipe de mission.",
      "Coter le risque de la mission (Faible / Modéré / Élevé) et justifier la cotation.",
      "Conclusion de l'associé : accepter / maintenir la mission.",
    ],
  },
};

const TEMPLATES: Record<string, WorkpaperTemplate> = {
  "D3.1": D31,
};

/** Resolve the template for a file-index code (falls back to the generic form). */
export function templateFor(code: string): WorkpaperTemplate {
  return TEMPLATES[code] ?? GENERIC;
}
