/**
 * The user-acceptance script: what a firm should exercise before trusting the
 * tool with a real audit, phase by phase, in the order an engagement runs.
 *
 * Grounded in the actual file index (lib/file-index.ts) rather than invented:
 * where a scenario names a task it names a real one — P6.1, S3.1, E1.2, C1.1 —
 * so a tester can find it and an auditor can see the coverage is the firm's own
 * methodology and not a generic checklist.
 *
 * Kept as data so the page can track a verdict and a note against each item and
 * count what is left. `key` is the stable identifier a stored result points at:
 * change the wording freely, never the key, or a tester's answers detach from
 * the question they answered.
 *
 * `path` is a real route. The page turns it into a link so a tester goes
 * straight to the screen; `:id` is replaced with the engagement they select.
 */

export type UatStatus = "not_started" | "passed" | "failed" | "blocked";

export interface UatScenario {
  key: string;
  title: string;
  /** The task code or standard this exercises — E1.2, ISA 240, and so on. */
  ref?: string;
  /** Why an auditor should care. Present where the answer is not obvious. */
  why?: string;
  /** Where to do it; `:id` becomes the selected engagement. */
  path?: string;
  steps: string[];
  expect: string;
}

export interface UatSection {
  key: string;
  title: string;
  intro: string;
  scenarios: UatScenario[];
}

/** Compact source form: [key, title, steps, expect, ref?, path?, why?] */
type Row = [string, string, string[], string, string?, string?, string?];

const rows = (prefix: string, list: Row[]): UatScenario[] =>
  list.map(([key, title, steps, expect, ref, path, why]) => ({
    key: `${prefix}.${key}`,
    title,
    steps,
    expect,
    ref,
    path,
    why,
  }));

// ─────────────────────────────────────────── the account working papers (E4.x)
// One test per account: the same procedure, a different balance each time —
// which is exactly how a firm works through a file, and why each deserves its
// own line rather than a single "check the lead schedules" tick.
const ACCOUNTS: [string, string][] = [
  ["E4.1", "Trade Receivables (E)"],
  ["E4.2", "Trade Payables (N)"],
  ["E4.3", "Inventories (F)"],
  ["E4.4", "Property, Plant & Equipment (K)"],
  ["E4.5", "Intangible Assets (L)"],
  ["E4.6", "Financial Assets (J)"],
  ["E4.7", "Cash & Cash Equivalents (C)"],
  ["E4.8", "Borrowings (Q)"],
  ["E4.9", "Share Capital & Reserves (T)"],
  ["E4.10", "Provisions for Risks & Charges (P1)"],
  ["E4.11", "Social & Payroll Liabilities (P2)"],
  ["E4.12", "Suspense & Deferred Income (P3)"],
  ["E4.14", "Tax Receivables (O1)"],
  ["E4.15", "Tax Payables (O2)"],
  ["E4.16", "Group & Associates — Short Term (I1)"],
  ["E4.18", "Other Current Assets (G2)"],
  ["E4.20", "Revenue (UA)"],
  ["E4.21", "Other Income (UB2)"],
  ["E4.22", "Finance Income (UC)"],
  ["E4.24", "Purchases (VA1)"],
  ["E4.25", "Change in Inventories (VA2)"],
  ["E4.26", "Personnel Costs (VB)"],
  ["E4.27", "Taxes & Duties (VO)"],
  // named as the lead-schedule tool names index VD1
  ["E4.28", "Non-Stored Purchases, Transport & External Services (VD1)"],
  ["E4.29", "Depreciation & Provisions (VD2)"],
  ["E4.31", "Other Expenses (VD4)"],
  ["E4.32", "Finance Costs (VD5)"],
  ["E4.34", "Income Tax (O4)"],
  ["E4.35", "Leases"],
  ["E4.36", "Cash Flow (TFT) Tie-out"],
];

// Leases and the TFT tie-out carry no lead index by design: no schedule to
// agree, only procedures, evidence and a conclusion.
const NO_LEAD_INDEX = new Set(["E4.35", "E4.36"]);

const accountPapers: UatScenario[] = ACCOUNTS.map(([code, name]) =>
  NO_LEAD_INDEX.has(code)
    ? {
        key: `exec.acct.${code.toLowerCase().replace(".", "-")}`,
        title: `${name} — procedures, evidence and conclusion`,
        ref: code,
        path: "/engagements/:id/phases/execution",
        why: `${code} has no lead-schedule index: the paper holds procedures and evidence, not a balance agreed to the trial balance.`,
        steps: [
          `Open ${code} from /groups/e4 or the execution phase list; it has no lead-schedule index, so it is listed even without an S5.5 design and holds procedures and evidence rather than a TB-agreed balance.`,
          "Add the custom procedures the work needs and record their results.",
          "Attach the supporting evidence to the task.",
          "Prepare the conclusion, have a second person review it, and sign P then R.",
        ],
        expect: `The procedures and their results are recorded, the evidence is attached to ${code}, and the conclusion shows a preparer and a reviewer.`,
      }
    : {
        key: `exec.acct.${code.toLowerCase().replace(".", "-")}`,
        title: `${name} — lead schedule and substantive work`,
        ref: code,
        path: "/engagements/:id/tools/lead-schedule",
        why: "The lead schedule is built by the tool from the imported trial balance; the E4 task appears only once S5.5 has selected procedures for its index.",
        steps: [
          "Precondition: import the trial balance (Trial Balance Analyzer) and select substantive procedures for this index in S5.5.",
          `Open Tools > Lead Schedule and agree the ${name} total to the trial balance for the same caption.`,
          `Open ${code} from /groups/e4, perform the selected procedures and attach the supporting schedule.`,
          "Prepare the conclusion, have a second person review it, and sign P then R.",
        ],
        expect: `The lead schedule agrees to the trial balance, the evidence is attached to ${code}, and the conclusion shows a preparer and a reviewer with the P and R sign-offs recorded.`,
      },
);

// ───────────────────────────────────────── the OHADA / statutory file (C5.x)
// [code, name, the check specific to the paper, what the tester expects]
const STATUTORY: [string, string, string, string][] = [
  [
    "C5.2",
    "Statutory Deadlines Calendar",
    "Confirm the AGO, filing and report dates the calendar computes from the period end match the Acte uniforme as your firm reads it.",
    "C5.2 is completed and evidenced, and the statutory dates it computes are the ones your firm would compute.",
  ],
  [
    "C5.3",
    "Regulated Agreements Register & Special Report",
    "Confirm every regulated agreement identified is on the register and the special report covers each one.",
    "C5.3 lists the agreements, the special report is generated for them, and the evidence is attached.",
  ],
  [
    "C5.4",
    "Article 715 Report to the Board",
    "Confirm the report names the matters article 715 requires and is dated before the board meeting.",
    "C5.4 is completed, the report is attached, and its date precedes the board meeting.",
  ],
  [
    "C5.5",
    "Alert Procedure File",
    "Confirm each phase of the alert procedure is recorded with its date and the response received.",
    "C5.5 records every phase of the procedure with dates and responses, and the correspondence is attached.",
  ],
  [
    "C5.6",
    "Disclosure of Criminal Offences to the Prosecutor",
    "Confirm the facts, the legal analysis and the decision to disclose or not are recorded; the paper computes no date.",
    "C5.6 records the facts, the analysis and the decision, and the supporting documents are attached.",
  ],
  [
    "C5.7",
    "Registered Securities Register Attestation",
    "Confirm the register was inspected and the attestation reflects its content at the date stated; the paper computes no threshold.",
    "C5.7 is completed, the attestation is attached, and it agrees to the register inspected.",
  ],
  [
    "C5.8",
    "Equity vs Half-of-Share-Capital Monitoring",
    "Confirm the equity and share-capital figures agree to the financial statements and the half-capital test reaches the conclusion your firm would reach.",
    "C5.8 shows the two figures agreed to the accounts and a conclusion consistent with article 664.",
  ],
  [
    "C5.9",
    "Joint Auditor Coordination File",
    "Confirm the work split, the cross-review and the joint conclusions are recorded with both firms named; the paper computes no date.",
    "C5.9 records the split, the cross-review and the joint conclusions, and the coordination correspondence is attached.",
  ],
  [
    "C5.10",
    "Article 525 Certification — Highest-Paid Persons' Remuneration",
    "Confirm the total certified agrees to the payroll records inspected; the paper computes no threshold.",
    "C5.10 is completed, the certification is attached, and the total agrees to the payroll evidence.",
  ],
];

const statutoryPapers: UatScenario[] = STATUTORY.map(([code, name, check, expect]) => ({
  key: `firm.stat.${code.toLowerCase().replace(".", "-")}`,
  title: `${name}`,
  ref: code,
  // the paper and its files live on the task page; /legal only hosts the
  // generators and monitoring panels (UAT B176)
  path: "/engagements/:id/tasks",
  steps: [
    `Open ${code} from /tasks and complete its working paper for this engagement.`,
    `Attach the supporting document or register in the task's files panel on ${code} (the /legal screen has no upload; use it only for the generators and panels).`,
    check,
  ],
  expect,
}));

export const UAT_SECTIONS: UatSection[] = [
  // ══════════════════════════════════════════════════════════════════ PHASE 0
  {
    key: "access",
    title: "Phase 0 · Access, onboarding and separation",
    intro:
      "Everything else depends on these, and the separation tests are the ones that matter most: if a colleague can open an engagement they are not on, nothing further is worth testing. Use at least three people — a firm administrator, a staff member on the engagement, and a staff member who is not — each on their own machine, not in a browser already signed in as you. Invitation and reset links travel by email and are stored only as a digest, so nobody can look them up afterwards. On an instance with no outgoing mail configured (the DEV instance), the message is not sent: the server log records the send with its recipient and subject, and the link exists nowhere. The invitation, reset and session scenarios below therefore need an instance with outgoing mail, with the tester's own mailbox as the recipient.",
    scenarios: rows("acc", [
      [
        "invite-new",
        "Invite a colleague who has never used the tool",
        [
          "Open Users and invite an address never used here.",
          "Type the full name as it should appear, initials and stops included.",
          "Ask them to open the email.",
        ],
        "The email names your firm, carries a link, and contains no password of any kind.",
        undefined,
        "/users",
        "Nobody should ever be sent a password. The link proves the person controls the mailbox; the password is theirs alone.",
      ],
      [
        "invite-setpw",
        "The invited person sets their own password",
        [
          "They click the link, choose a password and confirm it.",
          "They sign in with what they just chose.",
        ],
        "They reach the dashboard. No administrator ever knew the password.",
        undefined,
        undefined,
      ],
      [
        "invite-name",
        "The typed name is the name on the account",
        ["Look at the new colleague in Users and in the engagement team list."],
        "The name appears exactly as typed — not guessed from the email address.",
        undefined,
        "/users",
      ],
      [
        "invite-rules",
        "The password rules are stated before they are broken",
        [
          "On the invitation page, try a short password, then one with no capital letter, then one with no digit.",
        ],
        "Each refusal names the rule in plain language, and the rules are shown before the first attempt.",
        undefined,
      ],
      [
        "invite-mismatch",
        "Mistyping the confirmation is caught",
        ["Type two different passwords and submit."],
        "It says they do not match and nothing is saved.",
        undefined,
      ],
      [
        "invite-reuse",
        "A used invitation link stops working",
        ["Open the link a colleague has already used."],
        "It says the link is no longer valid and offers the sign-in page.",
        undefined,
      ],
      [
        "invite-supersede",
        "Re-inviting kills the previous link",
        ["Invite the same person again, then open the FIRST link."],
        "The first link no longer works; only the newest does.",
        undefined,
      ],
      [
        "invite-email-taken",
        "An address already used by another firm is refused",
        ["Try to add a colleague using an email that belongs to a user in a different firm."],
        "It is refused with a clear reason. One login never straddles two firms.",
        undefined,
        "/users",
      ],
      [
        "login-wrong",
        "A wrong password is refused without revealing anything",
        [
          "Sign in with a real address and a wrong password, then with an address that does not exist.",
        ],
        "Both give the same message. Neither reveals whether the address exists.",
        undefined,
        "/login",
      ],
      [
        "login-throttle",
        "Repeated guessing is slowed",
        ["Get the password wrong six or seven times in a row."],
        "You are told to wait. The delay grows with each attempt.",
        undefined,
        "/login",
      ],
      [
        "login-prefill",
        "The link in an email fills the address in",
        ["Open the sign-in link from an account email."],
        "The address is filled in and the cursor is in the password box.",
        undefined,
      ],
      [
        "login-next",
        "After signing in you land where the email pointed",
        ["Use an engagement invitation link, sign in."],
        "You arrive on that engagement, not on a generic dashboard.",
        undefined,
      ],
      [
        "login-openredirect",
        "A tampered link cannot send you off-site",
        ["Edit the sign-in URL so that next= points at another website, then sign in."],
        "You land inside AuditISA. The external address is ignored.",
        undefined,
      ],
      [
        "reset",
        "A firm administrator resets a password",
        [
          "Reset a colleague's password in Users.",
          "Confirm they get an email and can get back in.",
        ],
        "They regain access and choose a new password.",
        undefined,
        "/users",
      ],
      [
        "reset-sessions",
        "A reset closes the old session",
        [
          "With the colleague signed in elsewhere, reset their password.",
          "Have them refresh the page they were on.",
        ],
        "Their previous session is closed rather than continuing to work.",
        undefined,
        "/users",
        "A reset usually happens because something is wrong. It must not leave the old session alive.",
      ],
      [
        "change-own",
        "Changing your own password needs the current one",
        ["Open the change-password screen and try without the current password."],
        "It is refused. An unattended session cannot lock the owner out.",
        undefined,
        "/change-password",
      ],
      [
        "mfa-enrol",
        "Two-factor can be switched on",
        [
          "Prerequisite: an instance where the sign-in challenge is on (AUTH_DISABLE_MFA unset). The dev/staging site turns the challenge off, and /security says so; run this scenario on an instance with it on, or mark it blocked.",
          "Enrol an authenticator on your own account and sign out.",
          "Sign in again.",
        ],
        "Enrolment issues recovery codes once. On an instance with the challenge on, the code is requested at sign-in and accepted.",
        undefined,
        "/security",
        "Enrolment works everywhere; the challenge itself is what the staging instance switches off, so a missing code field there is the instance, not a defect.",
      ],
      [
        "mfa-recovery",
        "A recovery code works once",
        [
          "Prerequisite: an instance where the sign-in challenge is on (AUTH_DISABLE_MFA unset); otherwise mark this scenario blocked.",
          "Sign in using a recovery code instead of the app, then try the same code again.",
        ],
        "The first use works, the second is refused.",
        undefined,
        "/security",
      ],
      [
        "signout",
        "Signing out actually ends the session",
        ["Sign out, then press the browser Back button."],
        "You cannot see the file. Back does not restore the session.",
        undefined,
      ],
      [
        "session-expiry",
        "A revoked account stops working immediately",
        ["Remove a colleague from the firm while they are signed in.", "Have them click anything."],
        "They are signed out at once, not when the session happens to expire.",
        undefined,
        "/users",
      ],
      [
        "lang-login",
        "The language can be chosen before signing in",
        ["Switch to French on the sign-in page."],
        "The sign-in page is in French and stays French after signing in.",
        undefined,
        "/login",
      ],
      [
        "lang-persist",
        "The language survives moving around",
        ["In French, visit four different screens including an engagement."],
        "Every screen is French. Nothing reverts to English.",
        undefined,
      ],
      [
        "lang-docs",
        "Generated documents follow the language",
        ["In French, generate a working paper and open it."],
        "The document is French, not just the screen around it.",
        undefined,
      ],
      [
        "lang-switch-back",
        "Switching back to English works everywhere",
        ["Switch to English and revisit the same screens."],
        "All of them follow, including ones you had already opened in French.",
        undefined,
      ],
      [
        "sep-list",
        "A colleague does not see engagements they are not on",
        ["Sign in as a staff member not on a given engagement."],
        "That engagement is absent from their list.",
        undefined,
        "/engagements",
        "Inside one firm, an audit team is not everybody.",
      ],
      [
        "sep-url",
        "Guessing the address is not a way in",
        ["Copy an engagement URL from your browser into theirs."],
        "It does not open. The refusal does not reveal the client's name.",
        undefined,
      ],
      [
        "sep-task",
        "Nor is a deep link to a task",
        ["Send them a direct link to a working paper inside that engagement."],
        "Refused, and the refusal does not disclose the client or the paper's title.",
        undefined,
      ],
      [
        "sep-api",
        "Nor is a direct download link",
        ["Send them a direct link to an attachment's download URL."],
        "Refused. The file does not download.",
        undefined,
      ],
      [
        "sep-search",
        "Search does not reach across engagements",
        [
          "As that colleague, search for a client name or a document you know is in the engagement they are not on.",
        ],
        "Nothing from that engagement appears.",
        undefined,
        "/search",
      ],
      [
        "sep-assign",
        "Being added to the team and assigned a task grants access",
        [
          "Add that colleague to the engagement team (Team page) with a staff role — task assignment requires team membership.",
          "Assign them a task on the engagement.",
          "Have them refresh.",
        ],
        "The engagement now appears and opens. Access follows team membership and assignment.",
        undefined,
        "/engagements/:id/team",
      ],
      [
        "sep-unassign",
        "Removing them takes it away again",
        ["Remove them from the team and the task, and have them refresh."],
        "The engagement disappears from their list and the URL stops working.",
        undefined,
        "/engagements/:id/team",
      ],
      [
        "sep-partner",
        "A partner sees the whole portfolio",
        ["Sign in as a partner or firm administrator."],
        "Every engagement is listed, including ones they are not personally on. Confirm this matches how your firm expects oversight to work.",
        undefined,
        "/engagements",
        "ISQM 1 puts oversight of every engagement on the partner; scoping them to their own assignments would break it.",
      ],
      [
        "sep-portal-scope",
        "A client sees their requests and nothing else",
        ["Sign in to the portal as a client and look at what is offered."],
        "Their own document requests, and no part of the audit file.",
        undefined,
        "/engagements/:id/pbc",
      ],
      [
        "sep-portal-url",
        "A client cannot reach the file by URL",
        ["From the client's session, paste an engagement URL and a working-paper URL."],
        "Both refused. The portal is a door to their own requests, not to the audit file.",
        undefined,
      ],
      [
        "sep-portal-other",
        "A client cannot see another client's requests",
        [
          "Note the id of a document request belonging to client B (from B's PBC list at /engagements/:id/pbc).",
          "From client A's portal session, open that request's URL and its upload endpoint.",
        ],
        "Refused. One client never sees another client's requests or documents.",
        undefined,
        "/engagements/:id/pbc",
      ],
      [
        "sep-tenant",
        "Two firms cannot see each other at all",
        [
          "If you have a second firm on this instance, sign in to it and look for the first firm's clients, users and engagements.",
        ],
        "Nothing from the other firm is visible anywhere, including in search and in exports.",
        undefined,
      ],
      [
        "role-staff",
        "Staff cannot do partner things",
        ["As staff, try to approve materiality and to archive the engagement."],
        "Both refused, with a reason naming the role required.",
        undefined,
      ],
      [
        "role-change",
        "A role change takes effect at once",
        ["Promote a colleague to manager and have them sign in again."],
        "They can now do what a manager may do and still not what a partner may.",
        undefined,
        "/users",
      ],
      [
        "role-readonly",
        "A read-only user can look and not touch",
        ["Give someone read-only access and have them try to edit a paper."],
        "They can read the file and every change is refused.",
        undefined,
        "/users",
      ],
      [
        "role-remove",
        "Removing a colleague removes their access",
        ["Remove someone from the firm and have them try to sign in."],
        "They cannot sign in, and the refusal is the ordinary wrong-credentials message.",
        undefined,
        "/users",
      ],
      [
        "nav",
        "The main navigation reaches everything",
        [
          "From the dashboard, reach clients, engagements, users and settings (including the document templates), and from an engagement reach Tools > Sample papers.",
        ],
        "Every link works and lands on the right screen.",
        undefined,
        "/dashboard",
      ],
      [
        "dash-mytasks",
        "Your own tasks are on your dashboard",
        ["Assign yourself two tasks on different engagements and open the dashboard."],
        "Both appear, each naming its engagement, and clicking one opens it.",
        undefined,
        "/dashboard",
      ],
      [
        "dash-notify",
        "Being added to something tells you",
        ["Have a colleague add you to an engagement and raise a review note for you."],
        "Both appear as notifications.",
        undefined,
        "/dashboard",
      ],
      [
        "mobile",
        "It is usable on a phone or tablet",
        ["Open the dashboard and an engagement on a phone."],
        "Readable and navigable; nothing is cut off or unreachable.",
        undefined,
      ],
      [
        "browser",
        "It works in the browsers your firm uses",
        ["Repeat one sign-in and one working paper in each browser your firm uses."],
        "No difference in behaviour between them.",
        undefined,
      ],
    ]),
  },

  // ══════════════════════════════════════════════════════════════════ PHASE 1
  {
    key: "acceptance",
    title: "Phase 1 · Acceptance and continuance",
    intro:
      "The decision to take the work, and everything that must be settled before fieldwork can start. Take one real client you know well. Note anything your firm does at acceptance that the tool does not let you record.",
    scenarios: rows("acpt", [
      [
        "client-create",
        "Create a client",
        ["Create a client with its legal form, sector and registration details."],
        "The client is created and appears in the client register.",
        undefined,
        "/clients",
      ],
      [
        "client-edit",
        "Correct a client's details",
        ["Change the name and the legal form, and save."],
        "The change is saved and shows everywhere the client is named.",
        undefined,
        "/clients",
      ],
      [
        "client-duplicate",
        "Duplicate clients are noticed",
        ["Try to create a second client with the same name."],
        "You are warned, or the duplicate is visible enough to catch.",
        undefined,
        "/clients",
      ],
      [
        "eng-create",
        "Create an engagement",
        ["Create the engagement: financial year, period end, and the entity's characteristics."],
        "The engagement is created and opens.",
        undefined,
        "/new-engagement",
      ],
      [
        "eng-index",
        "The file index matches the entity",
        ["Look at the file index that was generated."],
        "A small non-complex entity does not carry a listed company's programme. The index reflects what you described.",
        undefined,
        "/engagements/:id",
      ],
      [
        "eng-naming",
        "The engagement is named to your convention",
        ["Check the engagement's name against your firm's naming convention in settings."],
        "It follows the convention, and changing the convention changes future engagements.",
        undefined,
        "/settings",
      ],
      [
        "eng-complexity",
        "Complexity changes the file",
        ["Create a second engagement with a different complexity and compare the two indexes."],
        "The programme differs in a way your firm would recognise as correct.",
        undefined,
        "/new-engagement",
      ],
      [
        "p11",
        "Consider client acceptance / continuance results",
        ["Complete P1.1 and record the conclusion."],
        "The task is completed, evidenced and signed.",
        "P1.1",
        "/engagements/:id/acceptance",
      ],
      [
        "p12",
        "Predecessor auditor communication",
        ["Open P1.2 from /groups/p1 (it is not on the acceptance page) and complete it, recording the communication or why none was required."],
        "Recorded with the reason, not silently skipped.",
        "P1.2",
        "/engagements/:id/groups/p1",
      ],
      [
        "p13",
        "Preconditions for an audit",
        ["Complete P1.3 and conclude on the preconditions."],
        "Completed and signed.",
        "P1.3",
        "/engagements/:id/acceptance",
      ],
      [
        "p14",
        "Engagement letter",
        ["Complete P1.4 and attach the signed engagement letter."],
        "The letter is attached and the task is signed.",
        "P1.4",
        "/engagements/:id/acceptance",
      ],
      [
        "p14-generate",
        "Generate the engagement letter from the file",
        ["Generate the engagement letter document rather than attaching your own."],
        "It carries your firm's letterhead and the client's details, in the chosen language.",
        "P1.4",
      ],
      [
        "p15",
        "Engagement quality review determination",
        [
          "Open P1.5 from /groups/p1 and record whether an EQR is required and why.",
          "Sign it off only after the independence scenarios (acpt.indep-*): P1.1 must be partner-signed, the independence confirmations answered, any declared exception dispositioned and the file in planning.",
        ],
        "The determination and its reasoning are recorded.",
        "P1.5",
        "/engagements/:id/groups/p1",
      ],
      [
        "indep-launch",
        "Issue independence confirmations to the team",
        ["Launch the independence campaign to the whole engagement team."],
        "Everyone on the team receives it.",
        undefined,
        "/engagements/:id/tools/independence",
      ],
      [
        "indep-respond",
        "Team members confirm independence",
        ["Have two colleagues respond, one confirming and one declaring a threat."],
        "Both responses are recorded and visible to the partner.",
        undefined,
      ],
      [
        "indep-threat",
        "A declared threat is not silently accepted",
        ["Look at the engagement after someone declares a threat."],
        "It is flagged for the partner rather than absorbed into a green tick.",
        undefined,
      ],
      [
        "indep-chase",
        "Outstanding confirmations are visible",
        ["Look at who has not responded."],
        "The outstanding list is obvious and chaseable.",
        undefined,
        "/engagements/:id/tools/independence",
      ],
      [
        "indep-late",
        "Someone added later is asked too",
        ["Add a new team member after the campaign was launched."],
        "They are asked to confirm as well, not missed.",
        undefined,
        "/engagements/:id/team",
      ],
      [
        "p21",
        "Independence and ethics conclusion",
        [
          "Precondition: the independence scenarios above are done — P1.1 is partner-signed, the confirmations are answered, any declared exception is dispositioned and the file is in planning.",
          "Open P2.1 from /groups/p2 and complete it.",
        ],
        "Completed and signed.",
        "P2.1",
        "/engagements/:id/groups/p2",
      ],
      [
        "p22",
        "Assess the team and specialised skills",
        ["Open P2.2 from /groups/p2 and complete it, recording the skills assessment."],
        "Completed and signed.",
        "P2.2",
        "/engagements/:id/groups/p2",
      ],
      [
        "p23",
        "Audit scope and components",
        ["Complete P2.3 for a group, recording the components and their scoping."],
        "Components and scoping decisions are recorded.",
        "P2.3",
        "/engagements/:id/groups/p2",
      ],
      [
        "team-partner",
        "Assign the engagement partner",
        ["Add the partner to the team."],
        "The partner appears and can sign partner-level items.",
        undefined,
        "/engagements/:id/team",
      ],
      [
        "team-manager",
        "Assign the manager and staff",
        ["Add a manager and two staff."],
        "All appear with their roles.",
        undefined,
        "/engagements/:id/team",
      ],
      [
        "team-eqr",
        "Assign the quality reviewer",
        ["Add an EQR reviewer to the team."],
        "They appear and can perform the review without being able to sign the work they review.",
        undefined,
        "/engagements/:id/team",
      ],
      [
        "team-many",
        "The team can be large",
        ["Add more than twenty people to the engagement."],
        "All are added. There is no cap.",
        undefined,
        "/engagements/:id/team",
      ],
      [
        "team-accept",
        "A member accepts the engagement",
        ["Have a colleague accept from their dashboard."],
        "Their status changes to accepted and is visible to the partner.",
        undefined,
      ],
      [
        "team-decline",
        "A member declines",
        ["Have a colleague decline."],
        "The decline is recorded with its reason and the partner can see it.",
        undefined,
      ],
      [
        "team-remove",
        "Removing a member is possible and recorded",
        ["Remove someone from the team."],
        "They lose access, and the change appears in the audit trail.",
        undefined,
        "/engagements/:id/team",
      ],
      [
        "team-roles",
        "Team roles drive what people may sign",
        ["As staff, try to sign something reserved for a manager."],
        "Refused, naming the role required.",
        undefined,
      ],
      [
        "gate-planning",
        "Acceptance gates planning",
        ["On the acceptance screen, before the acceptance gates are green, click 'Passer à la planification' (Advance to planning)."],
        "Refused, naming the outstanding gate.",
        undefined,
        "/engagements/:id/acceptance",
      ],
      [
        "gate-list",
        "Outstanding acceptance items are listed",
        ["Look at what acceptance says is still open."],
        "A specific list, not a generic 'incomplete'.",
        undefined,
        "/engagements/:id/acceptance",
      ],
      [
        "gate-pass",
        "Completing acceptance opens planning",
        ["Complete every acceptance item and try again."],
        "Planning opens, and the acceptance phase is shown as complete.",
        undefined,
      ],
      [
        "timeline",
        "Statutory dates are calculated",
        [
          "Check the period end shown on the legal screen (it comes from the engagement and is read-only there).",
          "Enter the planned AGM date and the planned report date, then click 'Save dates & refresh'.",
          "Click 'Generate / refresh calendar'.",
        ],
        "The statutory deadlines are computed — including the three that follow the AGM date — and match what your firm would compute.",
        "C5.2",
        "/engagements/:id/legal",
      ],
      [
        "continuance",
        "A continuing client is handled differently",
        ["Create a second-year engagement for the same client."],
        "It is recognised as continuance rather than a first-year acceptance.",
        undefined,
        "/new-engagement",
      ],
      [
        "prior-year",
        "Prior-year information carries forward",
        ["On the continuing engagement, look for prior-year balances and decisions."],
        "What should carry forward does, and what should not, does not.",
        undefined,
      ],
      [
        "opening",
        "Opening balances are addressed",
        ["Complete the opening-balances work for a first-year engagement."],
        "E6.5 is present and completable.",
        "E6.5",
        "/engagements/:id/groups/e6",
      ],
      [
        "docs-attach",
        "Attach acceptance evidence",
        ["Attach the signed acceptance memo and the letter."],
        "Both attach and download again correctly.",
        undefined,
      ],
      [
        "docs-version",
        "Replacing a document keeps the old one",
        ["Upload a corrected engagement letter over the first."],
        "Both versions are kept and the earlier one is still retrievable.",
        undefined,
      ],
      [
        "signoff-prep",
        "A preparer signs their own work",
        ["As the preparer, sign an acceptance task."],
        "The sign-off is recorded with name and time.",
        undefined,
      ],
      [
        "signoff-review",
        "A reviewer signs after the preparer",
        ["As the manager, review and sign the same task."],
        "Both sign-offs are recorded separately.",
        undefined,
      ],
      [
        "signoff-order",
        "A reviewer cannot sign before the preparer",
        ["Try to review a task nobody has prepared."],
        "Refused or clearly flagged.",
        undefined,
      ],
      [
        "signoff-invalidate",
        "Editing signed work invalidates the sign-off",
        ["Change an acceptance task after it was signed."],
        "The sign-off is invalidated rather than silently kept.",
        undefined,
        undefined,
        "A signature must mean the thing that was signed, not the thing it later became.",
      ],
      [
        "activity",
        "Acceptance decisions are in the audit trail",
        ["Open the activity trail and find the acceptance decisions."],
        "Each with who and when.",
        undefined,
        "/engagements/:id/activity",
      ],
      [
        "delete-guard",
        "An engagement is never deleted, only archived",
        ["Look for a way to delete the engagement on its settings page, on the register and on the dashboard."],
        "No delete is offered anywhere. A finished file is archived, and the archive keeps it readable. Nothing is lost by accident.",
        undefined,
        "/engagements/:id/settings",
      ],
      [
        "reopen",
        "The acceptance gate can be reopened deliberately",
        [
          "After acceptance, as the partner, open P1.1 from /documents/{id} and reopen it with a reason.",
          "Try the same as a manager once the partner has signed P1.1.",
        ],
        "Only the partner can reopen a partner-signed P1.1; its sign-offs are voided, the gate-reopened banner shows while the phase itself is unchanged, and the reopening is in the activity trail.",
        undefined,
      ],
    ]),
  },

  // ══════════════════════════════════════════════════════════════════ PHASE 2
  {
    key: "planning",
    title: "Phase 2 · Planning",
    intro:
      "Where the audit is designed. This is the phase most worth checking against how your firm actually works: the numbers, the risk assessment, and whether the programme that comes out the other end is the one you would have written.",
    scenarios: rows("plan", [
      [
        "p61-calc",
        "Determine materiality",
        ["Complete P6.1: benchmark, percentage, and the resulting PM, TE and SAD nominal amount."],
        "The three figures match the same calculation done by hand.",
        "P6.1",
        "/engagements/:id/tools/materiality",
      ],
      [
        "p61-benchmark",
        "Change the benchmark and the numbers follow",
        ["Switch the benchmark from result to revenue."],
        "Every dependent figure recalculates.",
        "P6.1",
        "/engagements/:id/tools/materiality",
      ],
      [
        "p61-te",
        "Performance materiality is a permitted fraction",
        ["Set performance materiality."],
        "Only the fractions your methodology permits are offered, and the reason for the choice is recorded.",
        "P6.1",
      ],
      [
        "p61-sad",
        "The SAD nominal amount is derived",
        ["Check the threshold for accumulating differences."],
        "It is derived from materiality, not typed freehand.",
        "P6.1",
      ],
      [
        "p61-specific",
        "Specific materiality for sensitive balances",
        ["Set a lower materiality for a specific account — related-party balances, say."],
        "It is recorded and applies to that account only.",
        "P6.1",
        "/engagements/:id/tools/materiality",
      ],
      [
        "p61-approve",
        "The partner approves materiality",
        ["Have the partner approve it."],
        "The approval is recorded with name and time.",
        "P6.1",
      ],
      [
        "p61-version",
        "Revising approved materiality creates a version",
        ["Change materiality after approval."],
        "A new version is created; the approved one is preserved, not overwritten.",
        "P6.1",
        undefined,
        "The figures behind a signed judgement have to still exist afterwards.",
      ],
      [
        "p61-propagate",
        "A materiality change reaches what depends on it",
        ["After revising materiality, look at sample sizes and the SAD."],
        "Both reflect the new figures.",
        "P6.1",
      ],
      [
        "p32",
        "Analytical risk assessment procedures",
        ["Complete P3.2 using the imported trial balance."],
        "The analytics run on real figures and the conclusions are recorded.",
        "P3.2",
        "/engagements/:id/tools/financial-analysis",
      ],
      [
        "p41",
        "Assess internal control at the entity level",
        ["Complete P4.1."],
        "Completed and signed.",
        "P4.1",
        "/engagements/:id/tools/forms",
      ],
      [
        "p42",
        "Control environment assessment",
        ["Answer yes to the S6.1 trigger 'detailed control-environment assessment', then complete P4.2."],
        "Completed and signed.",
        "P4.2",
        "/engagements/:id/tools/forms",
      ],
      [
        "p43",
        "Understand the IT environment",
        ["Answer yes to the S6.1 trigger 'IT environment assessment', then complete P4.3 and decide on IT specialist involvement."],
        "The decision and its basis are recorded.",
        "P4.3",
        "/engagements/:id/tools/forms",
      ],
      [
        "p51-fraud",
        "Identify fraud risks and responses",
        ["Complete P5.1, including the presumed revenue-recognition risk."],
        "Each fraud risk carries a response; rebutting the revenue presumption requires a reason.",
        "P5.1",
        "/engagements/:id/risks",
      ],
      [
        "p52-discussion",
        "The engagement team discussion",
        ["Open the P5.2 working paper from the P5 group and record the team discussion, listing who attended."],
        "Attendees, date and the matters discussed are recorded on the P5.2 paper.",
        "P5.2",
        "/engagements/:id/groups/p5",
      ],
      [
        "p62-accounts",
        "Identify significant accounts and assertions",
        ["Complete P6.2, marking significant accounts and the relevant assertions."],
        "Significance is driven by the figures and the risks, and can be overridden with a reason.",
        "P6.2",
        "/engagements/:id/tools/forms",
      ],
      [
        "s11-scots",
        "Identify significant classes of transactions",
        ["Complete S1.1 for revenue and for purchases."],
        "Both are recorded with the applications that process them.",
        "S1.1",
        "/engagements/:id/tools/forms",
      ],
      [
        "s12-wcgw",
        "Flows, what can go wrong, and controls",
        ["Complete S1.2: the flow of transactions, the WCGWs, and the controls addressing them."],
        "The chain from flow to risk to control holds together.",
        "S1.2",
        "/engagements/:id/tools/forms",
      ],
      [
        "s12-assertions",
        "Each WCGW carries assertions",
        ["Attach assertions to a what-can-go-wrong."],
        "Recorded, and they follow through to the risk assessment.",
        "S1.2",
      ],
      [
        "s13-walkthrough",
        "Perform walkthroughs",
        ["Complete S1.3 for one SCOT, attaching the walkthrough evidence."],
        "The walkthrough is documented against the flow it tested.",
        "S1.3",
        "/engagements/:id/tools/forms",
      ],
      [
        "s14-fscp",
        "Understand and evaluate the FSCP",
        ["Complete S1.4."],
        "Completed and signed.",
        "S1.4",
        "/engagements/:id/tools/forms",
      ],
      [
        "s21-select",
        "Select controls to test",
        ["Complete S2.1, marking which controls you intend to test."],
        "Only controls that address a WCGW can be selected.",
        "S2.1",
        "/engagements/:id/tools/forms",
      ],
      [
        "s22-design",
        "Design tests of controls",
        ["Complete S2.2 for a selected control: nature, timing and extent."],
        "The design is recorded and carries into execution.",
        "S2.2",
        "/engagements/:id/tools/forms",
      ],
      [
        "s23-itgc",
        "Understand ITGCs",
        ["Complete S2.3."],
        "Completed and signed.",
        "S2.3",
        "/engagements/:id/groups/s2",
      ],
      [
        "s24-itgc",
        "Design and execute ITGC tests",
        ["Complete S2.4."],
        "Completed and evidenced.",
        "S2.4",
      ],
      [
        "s25-itgc",
        "Evaluate ITGCs",
        ["Complete S2.5 and conclude."],
        "The conclusion is recorded and feeds the reliance decision.",
        "S2.5",
      ],
      [
        "s31-cra",
        "Make combined risk assessments",
        ["Complete S3.1: inherent and control risk per significant assertion."],
        "The register is complete and the assessments are per assertion, not per account.",
        "S3.1",
        "/engagements/:id/cra",
      ],
      [
        "s31-drives",
        "The assessment drives the programme",
        ["Change one assessment from low to high."],
        "The procedures proposed for that assertion change with it.",
        "S3.1",
        "/engagements/:id/cra",
        "A risk assessment that does not change the work is decoration.",
      ],
      [
        "s31-rely",
        "Choosing to rely on controls requires tests",
        ["Set an assertion to rely on controls without selecting a control to test."],
        "You are stopped or clearly warned.",
        "S3.1",
      ],
      [
        "s41-commit",
        "Commitments and contingencies",
        ["Complete S4.1."],
        "Completed and signed.",
        "S4.1",
      ],
      [
        "s42-gc",
        "Going concern — preliminary",
        ["Complete S4.2."],
        "Completed and signed.",
        "S4.2",
      ],
      [
        "s43-rp",
        "Related parties — planning",
        ["Complete S4.3, recording the related parties identified."],
        "The register is populated and carries into execution.",
        "S4.3",
      ],
      [
        "s44-est",
        "Accounting estimates — planning",
        ["Complete S4.4 for one estimate."],
        "The estimate, its method and the risk are recorded.",
        "S4.4",
      ],
      [
        "s51-expert",
        "Reliance on experts",
        ["Complete S5.1 for a valuation expert."],
        "Competence and objectivity are recorded, not assumed.",
        "S5.1",
      ],
      [
        "s52-service",
        "Service organisations",
        ["Complete S5.2."],
        "Completed, including how assurance over the service organisation is obtained.",
        "S5.2",
      ],
      ["s53-ia", "Internal audit", ["Complete S5.3."], "Completed and signed.", "S5.3"],
      [
        "s54-je",
        "Design journal-entry tests",
        ["Complete S5.4, recording the selection criteria."],
        "The criteria are risk-based and recorded before the testing.",
        "S5.4",
        "/engagements/:id/tools/je-selection",
      ],
      [
        "s55-subst",
        "Design substantive procedures",
        ["Complete S5.5 for a significant account."],
        "The procedures respond to the assessed risk for that assertion.",
        "S5.5",
        "/engagements/:id/tools/forms",
      ],
      [
        "s56-general",
        "Plan general audit procedures",
        ["Complete S5.6."],
        "Completed and signed.",
        "S5.6",
      ],
      [
        "s61-strategy",
        "Prepare the audit strategy memorandum",
        ["Complete S6.1 and generate the memorandum."],
        "It draws on the materiality, risks and scoping already recorded rather than asking again.",
        "S6.1",
        "/engagements/:id/planning",
      ],
      [
        "s62-direction",
        "Direction from the engagement partner",
        ["Complete S6.2."],
        "Completed and signed by the partner.",
        "S6.2",
      ],
      [
        "p71-govern",
        "Report to those charged with governance",
        ["Complete P7.1, then on the Acceptance page use 'Generate the planning communication (C5.1)'."],
        "The document is generated with the firm's letterhead and filed under C5.1.",
        "P7.1",
        "/engagements/:id/acceptance",
      ],
      [
        "p72-approve",
        "Planning review and approval",
        ["Complete P7.2 and have the partner approve planning."],
        "The approval is recorded.",
        "P7.2",
        "/engagements/:id/planning",
      ],
      [
        "gate-exec",
        "Planning gates execution",
        ["Before completing planning, try to move to execution."],
        "Refused, naming what is outstanding.",
        undefined,
        "/engagements/:id/phases/execution",
      ],
      [
        "budget",
        "Budget and time",
        ["Record a budget by phase and grade."],
        "The budget is saved and compares against time recorded later.",
        undefined,
        "/engagements/:id/time",
      ],
      [
        "tb-import-plan",
        "Import the trial balance for planning analytics",
        ["Import the draft trial balance."],
        "It imports, and P3.2 can use it.",
        undefined,
        "/engagements/:id/data",
      ],
      [
        "review-notes-plan",
        "Raise and clear a planning review note",
        ["Raise a review note on a planning paper and clear it."],
        "Raised, answered and cleared, with the history kept.",
        undefined,
        "/engagements/:id/tools/review-notes",
      ],
    ]),
  },

  // ══════════════════════════════════════════════════════════════════ PHASE 3
  {
    key: "execution",
    title: "Phase 3 · Execution",
    intro:
      "The bulk of the work. Use real documents — a scanned invoice, a bank confirmation, a messy spreadsheet — not placeholder files, so you see how it behaves with what you actually handle. The account working papers below are one per balance: work through the ones that matter for your client.",
    scenarios: [
      ...rows("exec", [
        [
          "tb-import",
          "Import a real trial balance",
          ["Import a trial balance exported from the client's system, untidied."],
          "It imports, or says precisely which rows it could not read.",
          undefined,
          "/engagements/:id/data",
        ],
        [
          "tb-messy",
          "A messy file fails loudly, not silently",
          ["Import a file with merged cells, blank rows and text in a number column."],
          "It names what it could not interpret rather than importing zeros.",
          undefined,
          "/engagements/:id/data",
          "A silently wrong trial balance is the worst possible outcome; a refusal is recoverable.",
        ],
        [
          "tb-balance",
          "The trial balance is checked to balance",
          ["Import a file that does not balance."],
          "You are told, with the difference.",
          undefined,
          "/engagements/:id/data",
        ],
        [
          "tb-map",
          "Accounts map to the financial-statement captions",
          ["Review the mapping to SYSCOHADA captions and correct one."],
          "The override is saved and used everywhere downstream.",
          undefined,
          "/engagements/:id/data",
        ],
        [
          "tb-prior",
          "Prior-year comparatives load",
          ["Import the prior-year trial balance."],
          "Comparatives appear beside the current year.",
          undefined,
          "/engagements/:id/data",
        ],
        [
          "tb-version",
          "Re-importing creates a version",
          ["Import a revised trial balance."],
          "The earlier version is kept and the change is visible.",
          undefined,
          "/engagements/:id/data",
        ],
        [
          "gl-import",
          "Import the general ledger",
          ["Import the GL detail."],
          "It imports and the console can query it.",
          undefined,
          "/engagements/:id/tools/gl-console",
        ],
        [
          "gl-query",
          "Interrogate the ledger",
          ["Filter the GL by account, period and amount."],
          "Results match the same filter in Excel.",
          undefined,
          "/engagements/:id/tools/gl-console",
        ],
        [
          "gl-drill",
          "Drill from a balance to its entries",
          ["From a lead schedule figure, open the entries behind it."],
          "The entries shown sum to the figure.",
          undefined,
          "/engagements/:id/tools/gl-console",
        ],
        [
          "subledger",
          "Import a sub-ledger and agree it",
          ["Import the receivables sub-ledger and agree it to the control account."],
          "The difference, if any, is shown.",
          undefined,
          "/engagements/:id/data",
        ],
        [
          "e11-itgc",
          "ITGC testing",
          ["Complete E1.1, recording the tests and results."],
          "Completed and evidenced.",
          "E1.1",
          "/engagements/:id/tools/forms",
        ],
        [
          "e12-effective",
          "Test a control and conclude effective",
          ["In E1.2 conclude that a selected control is effective."],
          "The conclusion is recorded against the control.",
          "E1.2",
          "/engagements/:id/tools/forms",
        ],
        [
          "e12-noteffective",
          "Concluding not effective changes the audit",
          ["Change the conclusion to not effective and open S3.1."],
          "The assertions that control covered are set to not rely on controls, with the reason recorded — without you having to remember.",
          "E1.2",
          "/engagements/:id/cra",
          "The assessment must never disagree with the test result.",
        ],
        [
          "e12-paper",
          "The testing itself is in a working paper",
          ["Open the standard tests-of-controls paper attached to the task."],
          "The attributes tested, the sample and the exceptions are documented there.",
          "E1.2",
        ],
        [
          "e21-update",
          "Update tests of controls after interim",
          ["Complete E2.1 for the roll-forward period."],
          "The roll-forward is documented and the period it covers is explicit.",
          "E2.1",
        ],
        [
          "sample-size",
          "A sample size matches your methodology",
          ["Define a population and draw a sample."],
          "The size matches your firm's own table.",
          undefined,
          "/engagements/:id/tools/sampling",
        ],
        [
          "sample-random",
          "The selection is random and reproducible",
          ["Draw the sample, then reopen the page."],
          "The same items are shown. It is not re-drawn each time.",
          undefined,
          "/engagements/:id/tools/sampling",
        ],
        [
          "sample-extract",
          "The selected items can be extracted",
          ["Export the sample."],
          "The export lists the selected items with enough detail to request them.",
          undefined,
          "/engagements/:id/tools/sampling",
        ],
        [
          "sample-key",
          "Key items are handled separately",
          ["Mark items above a threshold as key items."],
          "They are tested in full and not extrapolated.",
          undefined,
          "/engagements/:id/tools/sampling",
        ],
        [
          "sample-exception",
          "An exception is recorded and projected",
          ["Record an exception in the sample."],
          "It is recorded and its effect on the population is shown.",
          undefined,
          "/engagements/:id/tools/sampling",
        ],
        [
          "e31-je-load",
          "Load the journal file",
          ["Import the full journal listing for the year."],
          "It imports, with the row count agreed to the client's own count.",
          "E3.1",
          "/engagements/:id/tools/je-selection",
        ],
        [
          "e31-je-criteria",
          "Apply the journal selection criteria",
          [
            "Apply criteria — round amounts, unusual account pairings, weekend and public-holiday postings, and preparer = approver.",
            "Look for an out-of-hours criterion: there is none, because the ledger carries a posting date but no time of day; confirm the E3.1 workbook explains why out-of-hours postings are not testable.",
          ],
          "The entries selected are the ones the criteria describe, and the absence of an out-of-hours test is explained rather than silent.",
          "E3.1",
          "/engagements/:id/tools/je-selection",
        ],
        [
          "e31-je-notrandom",
          "Selection is risk-based, not random",
          ["Look at how the selection was made."],
          "It is driven by the criteria and explainable to a reviewer.",
          "E3.1",
        ],
        [
          "e31-je-test",
          "Test a selected journal entry",
          [
            "Document the testing of one selected entry: business rationale, accounting, cut-off, authorisation.",
          ],
          "All four are recorded against the entry.",
          "E3.1",
        ],
        [
          "analytics",
          "Run data analytics over the ledger",
          ["Run the analysers over the GL."],
          "The results are reproducible and the exceptions are actionable.",
          undefined,
          "/engagements/:id/tools/data-analytics",
        ],
        [
          "fin-analysis",
          "Financial analysis and ratios",
          ["Open the financial analysis for the current and prior year."],
          "Ratios and movements agree to the trial balance.",
          undefined,
          "/engagements/:id/tools/financial-analysis",
        ],
        [
          "attach-pdf",
          "Attach a PDF and get it back",
          ["Attach a scanned PDF to a task and download it."],
          "It downloads and opens identically.",
          undefined,
        ],
        [
          "attach-office",
          "Attach Word and Excel files",
          ["Attach a .docx and an .xlsx, then download both."],
          "Both open correctly in Office.",
          undefined,
        ],
        [
          "attach-large",
          "A large file is handled or refused clearly",
          ["Attach a file near the size limit, and one over it."],
          "The first attaches; the second is refused with the limit stated.",
          undefined,
        ],
        [
          "attach-version",
          "Re-uploading keeps both versions",
          ["Upload a corrected version of an attachment."],
          "Both versions are kept and the earlier one is retrievable.",
          undefined,
        ],
        [
          "attach-delete",
          "A deleted attachment can be recovered",
          ["Delete an attachment, then restore it."],
          "It comes back intact.",
          undefined,
        ],
        [
          "attach-rename",
          "An attachment can be renamed",
          ["Rename an attachment."],
          "The name changes and the file is unaffected.",
          undefined,
        ],
        [
          "attach-wrongtype",
          "A dangerous file type is refused",
          ["Try to attach an executable."],
          "Refused, naming the file types that are accepted.",
          undefined,
        ],
        [
          "wp-generate",
          "Generate a working paper from the file",
          ["Generate a working paper for a task."],
          "It is populated from the engagement's own data, in the chosen language, on the firm's letterhead.",
          undefined,
        ],
        [
          "wp-edit",
          "Edit a working paper and check it back in",
          ["Download it, edit it, upload it again."],
          "The new version is stored and the previous one preserved.",
          undefined,
        ],
        [
          "wp-lock",
          "Two people cannot overwrite each other",
          ["Have two people check the same paper out at once."],
          "The second is warned or blocked rather than silently overwriting.",
          undefined,
        ],
        [
          "review-raise",
          "Raise a review note",
          ["As manager, raise a note on a working paper and assign it."],
          "The preparer is notified.",
          undefined,
          "/engagements/:id/tools/review-notes",
        ],
        [
          "review-respond",
          "Respond and clear a note",
          ["Respond as the preparer; clear it as the manager."],
          "The exchange is kept in full, not just the outcome.",
          undefined,
        ],
        [
          "review-open",
          "Open notes are visible and block completion",
          ["Try to complete the phase with an open note."],
          "The open note is listed as outstanding.",
          undefined,
        ],
        [
          "signoff-task",
          "Sign off a completed task",
          ["Sign a task as preparer, then as reviewer."],
          "Both are recorded separately with name and time.",
          undefined,
        ],
        [
          "signoff-invalidate",
          "Changing signed work invalidates the sign-off",
          ["Edit a signed working paper."],
          "The sign-off is invalidated, not silently carried over.",
          undefined,
        ],
        [
          "assign",
          "Assign tasks to people",
          ["In Tools > Forms (or with the 'Assigned to' select on a working paper), assign several tasks to different people, with an owner and an approver."],
          "Each appears on the right person's dashboard.",
          undefined,
          "/engagements/:id/tools/forms",
        ],
        [
          "assign-phase",
          "Assign a whole phase at once",
          ["In Tools > Forms, assign every task in a phase to one person."],
          "All are assigned in one action.",
          undefined,
          "/engagements/:id/tools/forms",
        ],
        [
          "assign-unassigned",
          "Unassigned work is visible",
          ["In Tools > Forms, look for tasks nobody owns."],
          "They are listed rather than quietly forgotten.",
          undefined,
          "/engagements/:id/tools/forms",
        ],
        [
          "progress",
          "Progress reflects real sign-offs",
          ["Compare the progress shown with the tasks actually signed."],
          "The percentage counts signed work, not opened screens.",
          undefined,
          "/engagements/:id/dashboard",
        ],
        [
          "pbc-request",
          "Request documents from the client",
          ["Create several PBC requests."],
          "The client sees exactly those.",
          undefined,
          "/engagements/:id/pbc",
        ],
        [
          "pbc-upload",
          "The client uploads what was asked for",
          ["As the client, upload a document against a request."],
          "It arrives against that request and the team is notified.",
          undefined,
        ],
        [
          "pbc-accept",
          "Accept a client document into the file",
          ["Accept the uploaded document."],
          "It becomes evidence in the file with its hash recorded.",
          undefined,
        ],
        [
          "pbc-chase",
          "Outstanding requests are visible",
          ["Look at what is still outstanding."],
          "A clear list, chaseable.",
          undefined,
          "/engagements/:id/pbc",
        ],
        [
          "e61-noclar",
          "Laws and regulations / NOCLAR",
          ["Complete E6.1."],
          "Completed and signed.",
          "E6.1",
        ],
        [
          "e62-rp",
          "Related parties — execution",
          ["Complete E6.2 against the register from planning."],
          "The planning register carries through and is updated.",
          "E6.2",
        ],
        [
          "e63-gc",
          "Going concern",
          ["Complete E6.3, recording the assessment and the period covered."],
          "Completed and signed.",
          "E6.3",
        ],
        [
          "e64-minutes",
          "Minutes and statutory records",
          ["Complete E6.4 and attach the minutes reviewed."],
          "Completed and evidenced.",
          "E6.4",
        ],
        [
          "e65-opening",
          "Opening balances and comparatives",
          ["Complete E6.5."],
          "Completed and signed.",
          "E6.5",
        ],
        [
          "e66-subsequent",
          "Subsequent events — execution",
          ["Complete E6.6."],
          "Completed and signed.",
          "E6.6",
        ],
        [
          "e67-estimates",
          "Accounting estimates",
          ["Complete E6.7 for one estimate, including the range considered."],
          "The method, the assumptions and the conclusion are recorded.",
          "E6.7",
        ],
        [
          "e68-reassess",
          "Reassess the combined risk assessments",
          ["Complete E6.8 after the testing is done."],
          "Changes to the assessment are recorded with reasons.",
          "E6.8",
          "/engagements/:id/cra",
        ],
        [
          "e69-litigation",
          "Litigation and claims",
          ["Complete E6.9 and attach the lawyer's response."],
          "Completed and evidenced.",
          "E6.9",
        ],
        [
          "e610-fs",
          "Financial statement procedures",
          ["Complete E6.10, tying the accounts and notes out."],
          "The primary statements and the notes agree to the trial balance, and any difference is shown.",
          "E6.10",
        ],
        [
          "findings",
          "Raise a finding for the management letter",
          ["Raise a control deficiency as a finding."],
          "It carries a severity and flows to the management letter.",
          undefined,
          "/engagements/:id/findings",
        ],
        [
          "time",
          "Record time against the engagement",
          ["Record time for two people on different tasks."],
          "It totals against the budget.",
          undefined,
          "/engagements/:id/time",
        ],
      ]),
      ...accountPapers,
    ],
  },

  // ══════════════════════════════════════════════════════════════════ PHASE 4
  {
    key: "conclusion",
    title: "Phase 4 · Conclusion and archive",
    intro:
      "The end of the file, and the part that is hardest to undo. Read each scenario before doing it: archiving is meant to be irreversible, and you should see that for yourself on a test engagement rather than discover it on a real one.",
    scenarios: rows("concl", [
      [
        "sad-record",
        "Record a misstatement",
        ["Record a factual misstatement with its effect on profit and on the balance sheet."],
        "It appears on the SAD with both effects.",
        "C1.1",
        "/engagements/:id/tools/sad",
      ],
      [
        "sad-types",
        "Factual, judgemental and projected are distinguished",
        ["Record one of each."],
        "All three are held separately, as the standard requires.",
        "C1.1",
      ],
      [
        "sad-corrected",
        "Corrected and uncorrected are separated",
        ["Mark one misstatement as corrected by the client."],
        "It moves out of the uncorrected total.",
        "C1.1",
      ],
      [
        "sad-trivial",
        "Clearly trivial items are excluded",
        ["Record an item below the SAD nominal amount."],
        "It is excluded from accumulation, and the threshold used is visible.",
        "C1.1",
      ],
      [
        "sad-tax",
        "The tax effect is computed",
        ["Set the tax rate and look at the after-tax effect."],
        "It matches your own calculation.",
        "C1.1",
      ],
      [
        "sad-turnaround",
        "Prior-year turnaround is carried",
        ["Enter the turnaround from last year."],
        "It flows into the cumulative effect.",
        "C1.1",
      ],
      [
        "sad-threshold",
        "Uncorrected misstatements are compared to the right threshold",
        ["Check what the uncorrected total is measured against."],
        "Planning materiality less performance materiality — not performance materiality itself.",
        "C1.1",
        "/engagements/:id/tools/sad",
        "Comparing against the wrong figure roughly triples the tolerance and hides a breach.",
      ],
      [
        "sad-verdict",
        "The conclusion follows the numbers",
        ["Push the uncorrected total above the threshold."],
        "The verdict changes to say the threshold is exceeded.",
        "C1.1",
      ],
      [
        "sad-qualitative",
        "Qualitative factors are considered",
        ["Answer the qualitative factors."],
        "They are recorded alongside the arithmetic.",
        "C1.1",
      ],
      [
        "sad-export",
        "Export the SAD to Excel",
        ["Export it and compare with your own workbook."],
        "One tab per schedule, matching the layout your firm uses.",
        "C1.1",
      ],
      [
        "c12-srm",
        "Summary review memorandum",
        ["Complete C1.2."],
        "It draws on the file rather than asking for everything again.",
        "C1.2",
        "/engagements/:id/conclusion",
      ],
      [
        "c13-consult",
        "Consultation record",
        ["Complete C1.3 for a consultation."],
        "The matter, who was consulted and the conclusion are recorded.",
        "C1.3",
      ],
      [
        "c22-subsequent",
        "Subsequent events review",
        ["Complete C2.2 covering the period to the report date."],
        "The period covered is explicit.",
        "C2.2",
      ],
      [
        "c31-rep",
        "Management representation letter",
        ["Complete C3.1 and generate the letter."],
        "It is generated with the firm's letterhead and the matters from this file.",
        "C3.1",
      ],
      [
        "c41-review",
        "Review and approval summary",
        ["Complete C4.1."],
        "Completed and signed by the reviewer.",
        "C4.1",
      ],
      [
        "c42-eqr",
        "Engagement quality review",
        ["Complete C4.2 as the EQR reviewer."],
        "The reviewer can review without being able to sign the work they reviewed.",
        "C4.2",
      ],
      [
        "c42-eqr-gate",
        "The EQR must be complete before the report",
        ["Where an EQR was determined necessary, try to finish without it."],
        "Refused, naming the outstanding review.",
        "C4.2",
      ],
      [
        "c43-points",
        "Points outstanding",
        ["Complete C4.3, listing what remains."],
        "Open points are listed and block completion until cleared.",
        "C4.3",
      ],
      [
        "kam",
        "Key audit matters",
        ["Record the key audit matters, or record that there are none."],
        "Recording none requires a reason rather than being the silent default.",
        undefined,
        "/engagements/:id/conclusion",
      ],
      [
        "opinion",
        "Form the opinion",
        ["Record the opinion and any modification."],
        "A modification requires its basis to be recorded.",
        undefined,
        "/engagements/:id/conclusion",
      ],
      [
        "report-generate",
        "Generate the audit report",
        ["Generate the report."],
        "It carries the firm's letterhead, the client's details, the opinion and the KAMs from this file.",
        undefined,
      ],
      [
        "mgmt-letter",
        "Generate the management letter",
        ["Generate it from the findings raised during execution."],
        "Every finding raised appears, with its severity.",
        undefined,
        "/engagements/:id/findings",
      ],
      [
        "gov-report",
        "Report to those charged with governance",
        ["Generate the governance report."],
        "It includes uncorrected misstatements and significant deficiencies.",
        undefined,
      ],
      [
        "c61-checklist",
        "The archive checklist",
        ["Open C6.1 and look at what is outstanding."],
        "A specific list of gates and open items, not a generic message.",
        "C6.1",
        "/engagements/:id/conclusion",
      ],
      [
        "c61-gates",
        "Every gate is explained",
        ["For each outstanding gate, read what it wants."],
        "Each names the task or sign-off that is missing.",
        "C6.1",
      ],
      [
        "archive-blocked",
        "Archiving is refused while anything is open",
        ["Try to archive with an open review note and an unsigned task."],
        "Refused, listing both.",
        "C6.2",
        "/engagements/:id/conclusion",
      ],
      [
        "archive-do",
        "Archive the engagement",
        ["Clear everything and archive it."],
        "The engagement is archived and the retention date is set and shown.",
        "C6.2",
        "/engagements/:id/conclusion",
      ],
      [
        "archive-edit-paper",
        "An archived working paper cannot be edited",
        ["Try to edit a working paper in the archived engagement."],
        "Refused, and the message says the engagement is archived rather than failing obscurely.",
        "C6.2",
      ],
      [
        "archive-attach",
        "Nothing can be attached after archiving",
        ["Try to attach a document."],
        "Refused. An archived file takes no further evidence.",
        "C6.2",
      ],
      [
        "archive-note",
        "No review note can be added",
        ["Try to raise a review note."],
        "Refused. Review happens before archiving, not after.",
        "C6.2",
      ],
      [
        "archive-delete",
        "Nothing can be removed",
        ["Try to delete an attachment, un-complete a performed program step or clear a procedure result, and clear a saved working-paper answer on the archived file."],
        "All three refused with the archived-file message. Nothing can be removed from a file that has been archived.",
        "C6.2",
      ],
      [
        "archive-signoff",
        "No further sign-off is possible",
        ["Try to sign a task."],
        "Refused. The sign-offs are those that existed at archiving.",
        "C6.2",
      ],
      [
        "archive-team",
        "The team cannot be changed",
        ["Try to add or remove a team member."],
        "Refused. The team recorded on the file is the team that did the work.",
        "C6.2",
      ],
      [
        "archive-readable",
        "An archived file is still fully readable",
        ["Open the archived engagement and read a working paper and its evidence."],
        "Everything opens. Sealed is not the same as inaccessible.",
        "C6.2",
      ],
      [
        "archive-manifest",
        "A manifest records what was archived",
        ["Look at what was recorded at archiving."],
        "Every document and its hash, the sign-offs, and who archived it.",
        "C6.2",
      ],
      [
        "archive-retention",
        "The retention date is fixed",
        ["Change the firm's retention policy, then look at the archived engagement."],
        "Its retention date does not move. A later policy change cannot shorten a closed file.",
        "C6.2",
        "/settings",
      ],
      [
        "hold-place",
        "Place a legal hold",
        ["Place a legal hold on an engagement."],
        "It is recorded with its reason and who placed it.",
        undefined,
      ],
      [
        "hold-blocks",
        "A held engagement cannot be deleted",
        [
          "As firm admin and as partner, confirm that no delete-engagement action exists anywhere (the file can only be archived).",
          "As a platform super admin, on /admin run 'Delete firm' against a UAT firm that has a held engagement.",
        ],
        "Firm users have no way to delete the engagement; the firm deletion is refused with 'firm-has-legal-hold'.",
        undefined,
      ],
      [
        "hold-release",
        "Only a partner releases a hold",
        ["Try to release it as a manager, then as a partner."],
        "Refused, then allowed, and the release is recorded.",
        undefined,
      ],
      [
        "export-bundle",
        "Export the complete file",
        ["Export the whole engagement."],
        "The archive contains the working papers themselves, not an index of them.",
        undefined,
      ],
      [
        "export-verify",
        "The export can be verified",
        ["Check the checksum file against the contents."],
        "Every checksum verifies.",
        undefined,
      ],
      [
        "export-removed",
        "Deleted evidence is still accounted for",
        ["Look for the attachment you deleted earlier."],
        "It appears separately rather than vanishing from the record.",
        undefined,
      ],
      [
        "export-trail",
        "The audit trail is in the export",
        ["Find the activity log in the export."],
        "Present and complete.",
        undefined,
      ],
      [
        "reopen-archived",
        "Reopening an archived file is deliberate and recorded",
        ["Try to un-archive."],
        "Either refused outright, or possible only for a partner and recorded in the trail.",
        undefined,
      ],
      [
        "retention-report",
        "Files approaching their retention date are visible",
        ["Look for a view of retention dates across engagements."],
        "You can see which files are approaching destruction eligibility.",
        undefined,
      ],
    ]),
  },

  // ══════════════════════════════════════════════════════════════════ PHASE 5
  {
    key: "firm",
    title: "Phase 5 · Firm administration, statutory file and the platform",
    intro:
      "Running the firm rather than a single engagement, plus the OHADA statutory file that sits alongside the audit. Test as the firm administrator.",
    scenarios: [
      ...rows("firm", [
        [
          "brand-name",
          "Set the firm's display name",
          ["Set the firm's name in settings."],
          "It appears top-left in every engagement, on generated documents and on the client portal.",
          undefined,
          "/settings",
        ],
        [
          "brand-logo",
          "Upload the firm's logo",
          ["Upload a logo."],
          "It appears in the navigation and on generated documents.",
          undefined,
          "/settings",
        ],
        [
          "brand-colour",
          "Set the firm's accent colour",
          ["Choose an accent colour."],
          "The interface takes the colour and remains readable.",
          undefined,
          "/settings",
        ],
        [
          "brand-noleak",
          "No other firm's name appears anywhere",
          ["Look at the top-left, the documents and the portal."],
          "Only your firm's name and logo. No other firm's branding appears.",
          undefined,
          undefined,
          "A second firm's name on your screen is a tenancy failure, not a cosmetic one.",
        ],
        [
          "brand-letterhead",
          "Set the letterhead and footer",
          ["Set the address lines and the registration footer, then generate a letter."],
          "Both appear on the generated document.",
          undefined,
          "/settings",
        ],
        [
          "brand-naming",
          "Set the engagement naming convention",
          ["Change the convention and create an engagement."],
          "The new engagement follows it.",
          undefined,
          "/settings",
        ],
        [
          "retention-set",
          "Set the retention period",
          ["Set the firm's retention period."],
          "Only periods your jurisdiction permits are accepted; ten years is the default.",
          undefined,
          "/settings",
        ],
        [
          "users-list",
          "See everyone in the firm",
          ["Open Users."],
          "Everyone is listed with their role and status.",
          undefined,
          "/users",
        ],
        [
          "users-invite",
          "Invite several colleagues",
          ["Invite three people with different roles."],
          "Each receives an invitation appropriate to their role.",
          undefined,
          "/users",
        ],
        [
          "users-role",
          "Change a role",
          ["Change someone's role."],
          "It takes effect when they next load a page.",
          undefined,
          "/users",
        ],
        [
          "users-remove",
          "Remove someone",
          ["Remove a colleague who is on an engagement."],
          "You are warned about their engagements rather than silently orphaning the work.",
          undefined,
          "/users",
        ],
        [
          "clients-list",
          "The client register",
          ["Open the client list and search it."],
          "All clients are listed and search finds them.",
          undefined,
          "/clients",
        ],
        [
          "clients-archive",
          "Retire a client",
          ["Retire a client that is no longer served."],
          "It leaves the active list without deleting its history.",
          undefined,
          "/clients",
        ],
        [
          "portfolio",
          "See the whole portfolio",
          ["Open the engagement register as a partner."],
          "Every engagement with its phase, partner and progress.",
          undefined,
          "/engagements",
        ],
        [
          "portfolio-filter",
          "Filter the portfolio",
          ["Filter by phase and by partner."],
          "The filters work and can be combined.",
          undefined,
          "/engagements",
        ],
        [
          "search",
          "Search across the firm",
          ["Search for a client, an engagement and a document."],
          "All three are found, and only what you may see is returned.",
          undefined,
          "/search",
        ],
        [
          "resources",
          "The team workload view",
          [
            "Open Resources as a firm administrator.",
            "Open the same address as a partner, then as a staff member.",
          ],
          "The administrator sees every member of the firm with their role, open tasks, hours and engagements. Every other role is sent to the dashboard. Templates and guidance live under Templates, not here.",
          undefined,
          "/resources",
        ],
        [
          "templates",
          "Firm templates",
          ["Override a standard working-paper template with the firm's own."],
          "The override is used for new engagements.",
          undefined,
          "/templates",
        ],
        [
          "trail-find",
          "Find a change in the audit trail",
          ["Make a change, then find it in the trail."],
          "The entry names who made the change, what changed, and when, to the second.",
          undefined,
          "/engagements/:id/activity",
        ],
        [
          "trail-immutable",
          "The trail cannot be edited",
          ["Try to remove or change an entry."],
          "There is no way to do it.",
          undefined,
          "/engagements/:id/activity",
        ],
        [
          "trail-export",
          "The trail can be exported",
          ["Export the activity for an engagement."],
          "A complete record, readable outside the tool.",
          undefined,
        ],
        [
          "notifications",
          "Notifications reach the right people",
          ["Assign a task, raise a note and invite someone."],
          "Each reaches the intended person and nobody else.",
          undefined,
        ],
        [
          "email-deliver",
          "Emails actually arrive",
          ["Trigger an invitation, a reset and a PBC request."],
          "All three arrive, correctly addressed and branded.",
          undefined,
        ],
        [
          "perf-large",
          "A large engagement stays usable",
          ["Open an engagement with a full file index and a large ledger."],
          "Screens load in a time your team would accept.",
          undefined,
        ],
        [
          "perf-concurrent",
          "Several people working at once",
          ["Have four or five colleagues work in the same engagement simultaneously."],
          "No conflicts, no lost edits, no slowdown that stops work.",
          undefined,
        ],
        [
          "error",
          "An error explains itself",
          ["Provoke an error — an oversized upload, a malformed file."],
          "The message says what happened and what to do, not a stack trace or a blank page.",
          undefined,
        ],
        [
          "back",
          "The browser Back button behaves",
          ["Move through several screens and go back."],
          "You return where you expect, without losing unsaved work silently.",
          undefined,
        ],
        [
          "deeplink",
          "A link to a task can be shared",
          ["Copy a task URL and send it to a colleague on the engagement."],
          "It opens the task directly for them.",
          undefined,
        ],
        [
          "print",
          "Screens print legibly",
          ["Print a working paper and a lead schedule."],
          "Both print on one page width, with nothing cut off at the margin.",
          undefined,
        ],
        [
          "uat-record",
          "This workbook records your answers",
          ["Mark a scenario and write a note, then reload the page."],
          "Your verdict and note are still there.",
          undefined,
          "/uat",
        ],
        [
          "uat-collab",
          "Two testers do not overwrite each other",
          ["Have a colleague answer the same scenario differently."],
          "Both answers are visible, attributed to each of you.",
          undefined,
          "/uat",
        ],
        [
          "uat-notprod",
          "This workbook does not exist on production",
          ["Sign in to the production site and try /uat."],
          "The page does not exist on production — not merely hidden behind a permission.",
          undefined,
        ],
      ]),
      ...statutoryPapers,
      ...rows("stat", [
        [
          "alert",
          "The alert procedure escalates correctly",
          ["Record the first step of an alert procedure and follow it through."],
          "Each step's deadline is computed from the previous one.",
          "C5.5",
          "/engagements/:id/legal",
        ],
        [
          "equity",
          "Equity below half of share capital is detected",
          ["Enter a trial balance where equity has fallen below half the share capital."],
          "The monitoring flags it and points at the obligation that follows.",
          "C5.8",
        ],
        [
          "deadlines",
          "The statutory calendar is right",
          ["Compare every computed date with your own calculation from the Acte uniforme."],
          "Every computed deadline matches the date your firm would compute from the Acte uniforme.",
          "C5.2",
        ],
        [
          "joint",
          "Joint auditor coordination",
          ["Record the division of work with a joint auditor."],
          "The division and the cross-review are recorded.",
          "C5.9",
        ],
      ]),
    ],
  },
];

export const ALL_SCENARIOS: UatScenario[] = UAT_SECTIONS.flatMap((s) => s.scenarios);

/** Keys are the contract with stored results; a duplicate would silently merge two answers. */
export function duplicateKeys(): string[] {
  const seen = new Set<string>();
  const dupes: string[] = [];
  for (const s of ALL_SCENARIOS) {
    if (seen.has(s.key)) dupes.push(s.key);
    seen.add(s.key);
  }
  return dupes;
}

/** How many scenarios each phase carries — the page shows it, and a test floors it. */
export function sectionCounts(): { key: string; title: string; count: number }[] {
  return UAT_SECTIONS.map((s) => ({ key: s.key, title: s.title, count: s.scenarios.length }));
}
